import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

export default [
  // `next lint` (removed in Next 16) scoped linting to source dirs; `eslint .`
  // walks everything, so ignore build output and generated artifacts explicitly.
  // openapi-ts generated files are machine-generated — never lint/reformat by hand.
  {
    ignores: [
      "src/lib/api/generated/**",
      ".next/**",
      "playwright-report/**",
      "test-results/**",
      "coverage/**",
      "next-env.d.ts",
      "public/mockServiceWorker.js", // generated by MSW
    ],
  },
  // eslint-config-next 16 ships native flat configs (no more FlatCompat shim).
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // Config files legitimately use anonymous default exports.
    files: ["**/*.config.{js,mjs,ts}"],
    rules: { "import/no-anonymous-default-export": "off" },
  },
  {
    // react-hooks v7 (pulled in by eslint-config-next 16) adds stricter rules
    // that flag pre-existing, working code. Keep the Next 16 upgrade
    // behavior-preserving by surfacing these as warnings rather than hard
    // errors; the flagged patterns can be refactored in a dedicated follow-up.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/use-memo": "warn",
      "react-hooks/purity": "warn",
    },
  },
];
