import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

export default [
  // `next lint` (removed in Next 16) scoped linting to source dirs; `eslint .`
  // walks everything, so ignore build output and generated artifacts explicitly.
  // openapi-ts generated files are machine-generated — never lint/reformat by hand.
  {
    ignores: [
      "src/lib/api/generated/**",
      ".next/**",
      ".next-live/**", // custom dist dir used by the live build (NEXT_DIST_DIR)
      "playwright-report/**",
      "test-results/**",
      "coverage/**",
      "next-env.d.ts",
      "public/mockServiceWorker.js", // generated by MSW
      "public/otel-trace-sw.js", // vanilla service worker (serviceworker globals)
    ],
  },
  // eslint-config-next 16 ships native flat configs (no more FlatCompat shim).
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    // Config files legitimately use anonymous default exports.
    files: ["**/*.config.{js,mjs,ts}"],
    rules: { "import/no-anonymous-default-export": "off" },
  },
];
