services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=peepbot
      - POSTGRES_USER=peepbot
      - POSTGRES_DB=peepbot

volumes:
  database:
