services:
  db:
    image: postgres:17.5-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=peepbot
      - POSTGRES_USER=peepbot
      - POSTGRES_DB=peepbot

volumes:
  database:
