networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - dev

  api:
    image: ghcr.io/tyler-cash/tyler-bot-backend:latest
    container_name: api
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: "local"
    volumes:
      - database:/storage/
    ports:
      - "8080:8080"
    networks:
      - dev

  db:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tylerbot
      - POSTGRES_USER=tylerbot
      - POSTGRES_DB=tylerbot
    networks:
      - dev

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000
    volumes:
      - ./frontend/src:/code/src
    environment:
      REACT_APP_BACKEND_URI: http://localhost:8000
    networks:
      - dev
    depends_on:
      - api
volumes:
  database: