networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d/

  db:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=peepbot
      - POSTGRES_USER=peepbot
      - POSTGRES_DB=peepbot

volumes:
  database: