package dev.tylercash.event;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.data.web.config.EnableSpringDataWebSupport;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
@EnableAsync
@EnableCaching
@EnableRetry
@ConfigurationProperties
@EnableSpringDataWebSupport(pageSerializationMode = EnableSpringDataWebSupport.PageSerializationMode.VIA_DTO)
public class PeepBotApplication {

    public static void main(String[] args) {
        System.setProperty("java.awt.headless", "true");
        stampBuildInfoOntoOtelResource();
        SpringApplication.run(PeepBotApplication.class, args);
    }

    // Read META-INF/build-info.properties (generated by `springBoot.buildInfo`)
    // and stamp service.version + service.commit onto the Resource that Spring's
    // OpenTelemetry autoconfig builds for the SDK. Setting these as system
    // properties under `management.opentelemetry.resource-attributes[...]`
    // before Spring boots merges them into the Map the autoconfig binds, so
    // they apply to metrics, traces, and logs uniformly.
    private static void stampBuildInfoOntoOtelResource() {
        Properties build = new Properties();
        try (InputStream in = PeepBotApplication.class.getResourceAsStream("/META-INF/build-info.properties")) {
            if (in == null) return;
            build.load(in);
        } catch (IOException e) {
            return;
        }
        String version = build.getProperty("build.version");
        if (version != null && !version.isBlank()) {
            System.setProperty("management.opentelemetry.resource-attributes[service.version]", version);
        }
        String commit = build.getProperty("build.commit");
        if (commit != null && !commit.isBlank() && !"unknown".equals(commit)) {
            System.setProperty("management.opentelemetry.resource-attributes[service.commit]", commit);
        }
    }
}
