package dev.tylercash.event;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.data.web.config.EnableSpringDataWebSupport;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
@EnableAsync
@EnableCaching
@EnableRetry
@ConfigurationProperties
@EnableSpringDataWebSupport(pageSerializationMode = EnableSpringDataWebSupport.PageSerializationMode.VIA_DTO)
public class PeepBotApplication {

    public static void main(String[] args) {
        System.setProperty("java.awt.headless", "true");
        stampBuildInfoOntoOtelResource();
        SpringApplication.run(PeepBotApplication.class, args);
    }

    // Read META-INF/build-info.properties (generated by `springBoot.buildInfo`)
    // and append service.version + service.commit to otel.resource.attributes
    // before Spring's OTel autoconfiguration runs. Done as a system property so
    // it merges with any existing OTEL_RESOURCE_ATTRIBUTES env var rather than
    // replacing it.
    private static void stampBuildInfoOntoOtelResource() {
        Properties build = new Properties();
        try (InputStream in = PeepBotApplication.class.getResourceAsStream("/META-INF/build-info.properties")) {
            if (in == null) return;
            build.load(in);
        } catch (IOException e) {
            return;
        }
        StringBuilder add = new StringBuilder();
        String version = build.getProperty("build.version");
        if (version != null && !version.isBlank()) {
            add.append("service.version=").append(version);
        }
        String commit = build.getProperty("build.commit");
        if (commit != null && !commit.isBlank() && !"unknown".equals(commit)) {
            if (add.length() > 0) add.append(',');
            add.append("service.commit=").append(commit);
        }
        if (add.length() == 0) return;

        String existing = System.getProperty("otel.resource.attributes");
        String merged = (existing == null || existing.isBlank()) ? add.toString() : existing + "," + add;
        System.setProperty("otel.resource.attributes", merged);
    }
}
