dev.tylercash:
  cors:
    allowed-origins: https://event.tylercash.dev
  frontend:
    hostname: event.tylercash.dev
  immich:
    enabled: true
    album-name-prefix: ""
  rewind:
    normalisation-enabled: true

spring:
  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        enabled: true
