dev.tylercash:
  cors:
    allowed-origins:
      - https://event.tylercash.dev
  frontend:
    hostname: event.tylercash.dev
  immich:
    enabled: true
    album-name-prefix: ""
  rewind:
    normalisation-enabled: true
