on:
  push:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod -R +x .
      - run: ./gradlew clean build
      - run: docker build . -t ghcr.io/tyler-cash/tyler-bot-backend:latest
      - run: docker push ghcr.io/tyler-cash/tyler-bot-backend:latest

  frontend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: chmod -R +x .
      - run: docker build . -t ghcr.io/tyler-cash/tyler-bot-frontend:latest
      - run: docker push ghcr.io/tyler-cash/tyler-bot-frontend:latest
