on:
  push:
    branches: '**'
    paths:
      - '.github/backend.yml'
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      security-events: write
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod -R +x .

      - env:
          DEV_TYLERCASH_DISCORD_GUILD_ID: ${{ secrets.DEV_TYLERCASH_DISCORD_GUILD_ID }}
          DEV_TYLERCASH_DISCORD_TOKEN: ${{ secrets.DEV_TYLERCASH_DISCORD_TOKEN }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_CLIENT_SECRET }}
        run: ./gradlew clean build bootBuildImage cyclonedxBom

      - name: Scan SBOM (Grype)
        uses: anchore/scan-action@v6
        with:
          sbom: backend/build/reports/application.cdx.json
          output-file: &sarifOutput grype-backend.sarif
          severity-cutoff: high
          fail-build: true

      # doesn't work for some reason, I give up. Just makes it easier to interpret results.
      #      - name: Upload SARIF to GitHub Security
      #        uses: github/codeql-action/upload-sarif@v3
      #        if: always()
      #        with:
      #          sarif_file: *sarifOutput
      #          category: backend

      - if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/tyler-cash/peep-bot-backend:latest
