on:
  push:
    branches: '**'
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod -R +x .
      - run: ./gradlew clean build
      - run: docker build . -t ghcr.io/tyler-cash/tyler-bot-backend:latest
      - if: github.ref == 'refs/heads/master'
        run: docker push ghcr.io/tyler-cash/tyler-bot-backend:latest
