on:
  push:
    branches: '**'
    paths:
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: chmod -R +x .
      - run: docker build . -t ghcr.io/tyler-cash/peep-bot-frontend:latest
      - if: github.ref == 'refs/heads/master'
        run: docker push ghcr.io/tyler-cash/peep-bot-frontend:latest
