on:
  push:
    branches: '**'
    paths:
      - '.github/**'
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      security-events: write
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM (frontend)
        uses: anchore/sbom-action@v0
        with:
          path: ./frontend
          format: cyclonedx-json
          output-file: &sbomOutputFile sbom-frontend.cdx.json

      - name: Scan SBOM (Grype)
        uses: anchore/scan-action@v6
        with:
          sbom: *sbomOutputFile
          output-file: &grypeOutputFile grype-frontend.sarif
          severity-cutoff: critical
          fail-build: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: *grypeOutputFile

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - run: chmod -R +x .

      - run: docker build . -t ghcr.io/tyler-cash/peep-bot-frontend:latest

      - if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/tyler-cash/peep-bot-frontend:latest
