on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and test
        run: chmod -R +x backend && cd backend/ && ./gradlew clean bootBuildImage && docker push ghcr.io/tyler-cash/event-bot:latest
